name: 'C++ CI'

on: 
  push:
    branches:
      - main

jobs:
  build_macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Configure CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
      
      - name: Build and Install
        run: cmake --build . --target install
      
      - name: Package with CPack
        run: cpack -G ZIP
      
      - name: Check if package exists
        run: ls package
      
      - name: Create Release (MacOS)
        id: create_release_macos
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: macos-${{ github.run_number }}
          release_name: Release ${{ github.run_number }} (MacOS)
          draft: false
          prerelease: false
      
      - name: Upload Release Asset (MacOS)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: ./package/Guess_the_number-0.0.${{ github.run_number }}-Darwin.zip
          asset_name: Guess_the_number-0.0.${{ github.run_number }}-Darwin.zip
          asset_content_type: application/zip

  build_ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Configure CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      
      - name: Build
        run: cmake --build .
      
      - name: Package with CPack
        run: cpack -G ZIP
      
      - name: Check if package exists
        run: ls package
      
      - name: Create Release (Ubuntu)
        id: create_release_ubuntu
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ubuntu-${{ github.run_number }}
          release_name: Release ${{ github.run_number }} (Ubuntu)
          draft: false
          prerelease: false
      
      - name: Upload Release Asset (Ubuntu)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_ubuntu.outputs.upload_url }}
          asset_path: ./package/Guess_the_number-0.0.${{ github.run_number }}-Linux.zip
          asset_name: Guess_the_number-0.0.${{ github.run_number }}-Linux.zip
          asset_content_type: application/zip
